sudo: false

language: node_js
node_js: node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - echo "[ Test ] Init build"

install:
  - yarn install

script:
  - yarn run test

after_success:
  - echo "[ Test ] Build success"

after_failure:
  - echo "[ Test ] Build failure"

cache:
  yarn: true
